### ISSUE TITLE
When tag passed in to the playbook e.g level1-server, a number of plays that should run, do not

### ISSUE THREAD

**Issue by vishghelani** [ansible-lockdown/RHEL8-CIS#231]
**Describe the Issue**
When the playbook is run with a tag passed in (e.g. level1-server) a number of tasks such as:
 - SECTION | 1.6 | Mandatory Access Control
 - SECTION | 4.2.1.x| Configure rsyslog
 - SECTION | 3.4.2.x | Configure nftables
are not running

**Expected Behavior**
These included sections should run and the tags within the individual tasks should drive whether they are skipped or not

**Actual Behavior**
The entire section is being skipped (when a tag is passed in)

**Environment (please complete the following information):**
 - Ansible Version: Ansible 2.13.5
 - Host Python Version: Python 3.8.10
 - Using branch:  main, tag v2.1.0
 - Additional Details:

**Possible Solution**
These tasks are being called via include_tasks (without tags) and thus are being skipped over (when a tag is passed). If these are changed to import_tasks the tasks will be statically imported and thus each task can be can run or be skipped based on the tag passed into the playbook. Alternatively tags could be passed in against the included tasks.

**Comment by uk-bolly** [comment]
Hi @vishghelani 

Thank you for taking the time to feedback on this issue and provide pointers on where the issues exist.
The majority are included in the outstanding PR. I have since updated with those which were not correct. This should be resolved when the PR is merged.

Thank you once again

uk-bolly

**Comment by georgenalen** [comment]
This looks to be resolved based on @uk-bolly's comment. I just tested (with what's in devel) and using the level tags I was able to run just the level controls that were intended with no incorrect skips. I will close this on the next release since it sounds like there were changes to the role to fix this issue. 

-George
