### ISSUE TITLE
Encountered an error when scanning a server that is not connected to the internet

### ISSUE THREAD

**Issue by jamhulk** [ansible-lockdown/RHEL8-CIS#316]
**Describe the Issue**

as stated, an error encountered when scanning a server that is offline or not connected to the internet.

**Actual Behavior**
playbook stops when executing the downloading task.
Ex. Downloading the goss binary and cloning the git repo etc

**Control(s) Affected**
All

Note:
Tried to manually download the goss binary ang execute the playbook again and it continue to play until it reaches the downloading of the git repo part.

**Comment by uk-bolly** [comment]
hi @jamhulk 

Thank you for raising this issue, the goss binary it is possible to use without being connected to the internet. You can change several settings in the audit components from run_audit: false to changing the way it gets the content e.g. copy instead of using git.
Hopefully this diagram is of some assistance. https://ansible-lockdown.readthedocs.io/en/latest/combined/comb-getting-started.html
Please let us know or feel free to drop into discord https://discord.io/ansible-lockdown where others maybe able to help.

kindest

uk-bolly

**Comment by uk-bolly** [comment]
hi @jamhulk 

Please let us know if this doesn't answer your questions or if you require any further assistance.

many thanks

uk-bolly

**Comment by jamhulk** [comment]
Hi @uk-bolly,

Apoligies for the late reply. 
I have not yet tested again the program. 
Hopefully I could try your suggestion next week. 
I'll drop another update here. 

Thanks

**Comment by uk-bolly** [comment]
Closed as stale
